"""empty message

Revision ID: f94aa916bc27
Revises: 9ad611551dd6
Create Date: 2024-07-18 17:50:13.348639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f94aa916bc27'
down_revision = '9ad611551dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageUrl', sa.String(), nullable=False))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('imageUrl')

    # ### end Alembic commands ###
